<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.xytang</groupId>
    <artifactId>spring-cloud-common</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <modules>
        <module>spring-cloud-common-core</module>
        <module>spring-cloud-common-redis</module>
        <module>spring-cloud-common-redisson</module>
        <module>spring-cloud-common-mybatis</module>
        <module>spring-cloud-common-datasource</module>
        <module>spring-cloud-common-mq</module>
        <module>spring-cloud-common-mongo</module>
        <module>spring-cloud-common-es</module>
        <module>spring-cloud-common-ai</module>
        <module>spring-cloud-common-satoken</module>
        <module>spring-cloud-common-security</module>
        <module>spring-cloud-common-web</module>
        <module>spring-cloud-common-log</module>
        <module>spring-cloud-common-swagger</module>
        <module>spring-cloud-common-cache</module>
        <module>spring-cloud-common-netty</module>
        <module>spring-cloud-common-test</module>
    </modules>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

</project>